### ISSUE TITLE
repository key in package.json is incorrect making npm function incorrectly

### ISSUE THREAD

**Issue by mrpotatoes** [wappsify/react-static-plugin-file-watch-reload#2]
A normal user
1. https://www.npmjs.com/package/react-static-plugin-file-watch-reload
1. Click "`Repository`" or "`Homepage`"
1. Goes to `https://github.com/wappsify/react-static-file-watch-reload`

Your `package.json` has the `repository` key set to `https://github.com/wappsify/react-static-file-watch-reload` when it should be `https://github.com/wappsify/react-static-plugin-file-watch-reload`

To compare easier
* `https://github.com/wappsify/react-static-file-watch-reload`
* `https://github.com/wappsify/react-static-plugin-file-watch-reload`

**Comment by wappsify** [comment]
Just released v1.0.3, where this is fixed! Thanks!
